--- #YAML:1.0
name:               Microarray-ExprSet
version:            0.11
abstract:           Simple description of microarray data
author:
    - Zuguang Gu <jokergoo@gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:             0
    List::Vectorize:  1.00
    Test::More:       0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
